version: '3'
services:
  db:
    image: mariadb:10.2.12
    ports:
      - "24306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_PORT=3306
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  api:
    build: ./
    restart: always
    command: uwsgi --ini uwsgi
